version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    # Dependabot 버전 업데이트 PR 생성 비활성화
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: 'expo*'
      - dependency-name: 'react-native*'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react'
      - dependency-name: '@sentry/react-native'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tailwindcss'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jest'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/jest'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    # Dependabot 버전 업데이트 PR 생성 비활성화
    open-pull-requests-limit: 0
